

# simulating branching process
simulate <- function(N, lambda, nb_children) {
	die <- 0
    z_values <- c()
    z_values[1] <- 1; z_values[2] <- 1; z_values[3] <- 2; z_values[4] <- 5; z_values[5] <- 7
   
	# start generating children from generation 5.
    for (i in 6:N){
	if(z_values[i-1] > nb_children){
		die = 0
		break
	}
    if(z_values[i-1]==0){
		z_values[i]=0; die = 1
		break
	}
	else {
        x=rpois(z_values[i-1], lambda) 
        z_values[i] = sum(x)
        }
    }
    return(die)
}

n = 100000
lambdas <- rgamma(n = n, shape = 15, rate = 9)
max_generation = 100; nb_children = 100
counter = 0
for(i in 1:n){
	extinct <- simulate(max_generation, lambdas[i], nb_children)
	if(extinct == 1){
		counter <- counter + 1
	}
}
print(counter/n)
cat("probability of extinction where lambdas generated by gamma =", counter/n)


counter <- 0
for(i in 1:n){
	Zn <- simulate(max_generation, 1.6, nb_children)
	if(Zn == 1){
		counter <- counter + 1
	}
}
cat("\nprobability of extinction where lambda is 1.6 =", counter/n)


